[phases.setup]
nixPkgs = ["php81", "php81Extensions.common", "php81Extensions.curl", "php81Extensions.mbstring", "php81Extensions.openssl", "php81Extensions.pdo", "php81Extensions.pdo_mysql", "php81Extensions.tokenizer", "php81Extensions.fileinfo", "openssl", "nodejs", "npm"]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "php artisan key:generate",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"